### ISSUE TITLE
Preferenciák kialakítása

### ISSUE THREAD

**Issue by Zsolt05** [BHBNoteShare/NoteShare#12]
- [x] Modellek hozzáadása (Entity + Dto)
- [x] Service hozzáadása
- [x] Végpontok hozzáadása
  - [x] subjectek lapozott lekérdezése[Auth]
  - [x] iskolák lapozott lekérdezése
  - [x] preferenciák hozzáadása[Auth]
  - [x] preferenciák törlése[Auth]

**Comment by BojszaReka** [comment]
- [x]  tárgyak keresése név alapján (ékezetek/nélküle, min 3 betű)
- [x] iskolák kereséses név és om azonosító alapján
