### ISSUE TITLE
Bejelentkező felület kialakítása

### ISSUE THREAD

**Issue by BojszaReka** [BHBNoteShare/NoteShare#2]
Bejelentkezési módok: 
•	email + jelszó kombináció
Hozzá tartozó további funkciók:
•	Nincs fiókod? -> regisztrációs felületre átirányítás

(elfelejtett jelszónak hely)

![NoteShare](https://github.com/BHBNoteShare/NoteShare/assets/113019065/79596bb3-6316-4684-8998-264c044dac09)

**Comment by KornelHajto** [comment]
## Jelenlegi haladás

![Image](https://github.com/BHBNoteShare/NoteShare/assets/72157420/7fe06f80-7d3e-40e7-85b6-c30273ee26e7)
